### ISSUE TITLE
add nlminb support for MHRM?

### ISSUE THREAD

**Issue by genwei007** [philchalmers/mirt#105]
Hi Phil,
Will nlminb be added? I would like to check whether nlminb could perform better than optim. Thank you.

**Comment by philchalmers** [comment]
It's possible, but I very much doubt it would make a difference. The majority of the estimation variability comes from the stochastic MH step, where the optimiser makes very little different due to how much noise there is in the imputations. I simply included these optimizers to make a more kosher SEM/SAEM algorithm where a real M-step was being performed (as opposed to the MH-RM, which only does a single Newton-Raphson update).
