### ISSUE TITLE
parameter modification of the GRSM model

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#127]
Hello, Phil.

I want to modify parameters on the grsm, but I can not do that.

Could you check this?

Best,
Seongho

```R
> # parameter passing test
>   mod1 <- mirt::mirt(mirt::Science, 2, pars = 'values', method = 'QMCEM') # GRM
>   mod1$est <- F
>   mod1Prime <- mirt::mirt(mirt::Science, 2, pars = mod1, method = 'QMCEM') # PASSED
>   
>   mod2 <- mirt::mirt(mirt::Science, 2, itemtype = 'grsm', pars = 'values', method = 'QMCEM') # GRSM
>   mod2$est <- F
>   mod2Prime <- mirt::mirt(mirt::Science, 2, itemtype = 'grsm', pars = mod2, method = 'QMCEM')
Error: Constraint applied to fixed parameter(s) 3 4 5 9 10 11 15 16 17 21 22 23  but should only be applied to estimated parameters. Please fix!
```

**Comment by philchalmers** [comment]
Hey Seongho,

Not really a bug, but pretty close. If you want to disable the automatic internal constraints in mirt then pass `technical = list(internal_constraints = FALSE)`. What's going on here is mirt is trying to automatically add constraints to these trailing intercept terms, but is getting mad after it realises all of them were fixed rather than estimated.

**Comment by seonghobae** [comment]
Cool, that may need to notice somewhere to know every person.

**Comment by philchalmers** [comment]
It's in the `?mirt` help-file, though admittedly that HTML document has become very cluttered due to the complexity of the functions.
