### ISSUE TITLE
The Options$exploratory is FALSE when calibrate exploratory model in mixedmirt()

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#129]
Hello, Phil.

I found the confused about of Options$exploratory. I tried to calibrate exploratory model in mixedmirt(), but Options$exploratory has FALSE.

That's correct behaviour in mixedmirt?

Seongho

```R
> test <- mirt::mixedmirt(mirt::Science, covdata = mirt::Science, model = 2, itemtype = 'graded')
Stage 3 = 148, LL = -2419.1, AR(1.80) = [0.30], gam = 0.0042, Max-Change = 0.0007

Calculating information matrix...

Calculating log-likelihood...
> test@Options$exploratory
[1] FALSE
```

**Comment by philchalmers** [comment]
Yes, this is generally deliberate because of the flexibility in `mixedmirt()`. Because the model form could be something other than exploratory, and because it's mostly only useful *after* a latent variable structure has been determined, I set this slot to FALSE so that rotation is not performed automatically by secondary functions. So basically, what you've fitted here really should be reserved for `mirt()`.

**Comment by seonghobae** [comment]
Okay, so that is correct, then you meant that is the unrotated exploratory model itself but nothing to change to an exploratory flag FALSE to TRUE?

**Comment by philchalmers** [comment]
Exactly. You could probably change this flag yourself post-estimation, but
I have tested if there would be unwanted consequences by doing so.

Phil
