### ISSUE TITLE
NA values in Nominal Response Model when there is a missing distractor

### ISSUE THREAD

**Issue by aureliogarcia** [philchalmers/mirt#135]
Hi Phil,

I had this behaviour when fitting a Nominal response model  via ` nrm <- mirt(test_data, 1, 'nominal')`

The dataset includes the data from a 100 item test with 4-choice answers and 400 test takers. The answers for just one item include only 3 out of the 4 possible answers (it includes answers 1,2 and 4, after recoding the answers to match the key with value 4). All the other item answers include the four possible choices and empty answers).

The issue is that when fitting the Nominal Response Model, for the item with a missing distractor I get NA values for a4 and c4 from `coef(nrm, simplify = T, IRTpars = T)$item`. So it is not possible to compute probabilities for the right answer to this question.

Thanks so much for your effort.

**Comment by philchalmers** [comment]
This is a feature, not a bug. You'll also notice something like "Item re-scored so that all values are within a distance of 1" to reflect that all 4's in the 1,2,4 combination are rewritten to 1,2,3, for technical internal reasons. For the nominal response model this is irrelevant though since the scoring coefficients do not matter. The NA from simplify=TRUE just reflects that this item only had three nominal response categories. HTH.

**Comment by seonghobae** [comment]
In my knowledge, That seems odd item. Distractor seems not working now. If the chance of selecting of one of the distractors is zero, That's functioning 3-choice, not 4-choice. Exclude that item from the pool.

**Comment by aureliogarcia** [comment]
Thanks so much.
