### ISSUE TITLE
Could not run mod2values() on development version

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#137]
[parnames_not_found.zip](https://github.com/philchalmers/mirt/files/1777364/parnames_not_found.zip)
Can you see the any parameters via mod2values with development version?
I can not see the any parameters what I attatched model with mixedmirt().
The CRAN version is good. Just for the development version.

Best,
Seongho

**Comment by philchalmers** [comment]
There's no guarantee that previously objects fitted with previous version of `mirt` will work in the future; hence, you'd need to refit the model with the latest version and use that instead of this older object. What changed here is that the internal item parameter labels are now stored in a `@parnames` slot for easier tracking, which did not exist previously.
