### ISSUE TITLE
questions about information matrix estimation 

### ISSUE THREAD

**Issue by mileysmiley** [philchalmers/mirt#139]
Mr.Chalmers,

1.What's the difference between sandwich.Louis and sandwich(using oakes method). Do they only differ in efficiency but end up with the same estimated value of se?
2. in mirt function, how do we seperately record the consumed time of EM algorithm and the elapsed time of standard error estimation?

Thanks,
Miley

**Comment by philchalmers** [comment]
1. Yes. They are mathematically equivalent but use different estimators for the components.
2. Use the `extract.mirt()` function and pull out the associated time element.

Also, please use the mirt-package forum rather than opening issues. This Github location is for code-related bugs and features, not general query's .

**Comment by mileysmiley** [comment]
Thanks for your reply.
 Another question is that I found it seems that most often  louis method, forward, Richardson option give estimated value of standard error with very little difference, while results of other methods may differ , which means the results of the three methods are aligned. Could you explain the reason and does that imply that these three methods are suggested as the optimal choice( if ignore the elapsed time of estimation)?
