### ISSUE TITLE
bfactor and MHRM

### ISSUE THREAD

**Issue by Pip-griff** [philchalmers/mirt#192]
Hi Phil,
I may be wrong here (and I am not sure this is an issue as such), but it seems that the bfactor model cannot be set up to use model = "MHRM". I have tried running a longitudinal IRT model with between 3 and 7 timepoints in mirt and the quadrature is an issue. Either quadrature is is too low to reach a solution, or too high for memory allocation.

Could bfactor be set up to include MHRM, or is there something which would prevent stochastic methods here?

thanks!
Pip

**Comment by philchalmers** [comment]
Thanks, Pip. This is actually by design since `bfactor()` provides a specific data-reduction integration approach that doesn't generalize to everything else that mirt supports; hence, this function has been isolated from the more central `mirt()` function. That said, you can reproduce the fitted `bfactor()` models in `mirt()` just by specifying a suitable syntax and using the `'MHRM'` algorithm as you've requested.

**Comment by Pip-griff** [comment]
Thanks for this Phil,

I have now found the google groups and I will post there in future. 

Now I am off to try and build the model in mirt()
