### ISSUE TITLE
Including inter-item correlations into a model

### ISSUE THREAD

**Issue by netique** [philchalmers/mirt#206]
I have been working with two-tier/bifactor/testlet models lately and stumbled upon the residuals emerging from unmodelled relationships between several items spanning across latent factors, see the red lines in the diagramm:

![cfa_diagramm](https://user-images.githubusercontent.com/34926852/127073829-ce400261-e359-449a-8ab5-8def7289d356.png)

In CFA setting, say using the `lavaan` package, one can easily include those into the model and estimate the covariances when in theory, the items should be in fact correlated to the substantial degree (numbers in the picture are only for illustrational purpose).

I have tried pretty hard to come with any meaningful solution to my problem, but with no success. In `mirt`, one can specify the relationships between the latent factors, but the documentation is silent about the observed variables / indicators. I was thinking about some constrain "magic", but I do not see the way out there. Do you have any proposals, hints or solution to this issue?

Many thanks!

**Comment by philchalmers** [comment]
This isn't really an issue with mirt, and questions like these would be better suited on the mirt-package forum. I'll answer here just for convenience, but please try to post there in the future. 

Covarying results is not something that is possible when the response variables are discrete because of the model-implied expected values are not independent from the residuals. Hence, in order to obtain this type of residual correlation effect you could approach the problem by thinking about bivariate covariance terms as the presence of a single unique factor to those items, though for identification purposes you would have to constrain their respective slope parameters to be equal.
