### ISSUE TITLE
Score function for GRSM?

### ISSUE THREAD

**Issue by marerikri** [philchalmers/mirt#223]
I'm interested in obtaining the score matrix — the matrix of individual lnL derivatives, for example as is obtained from estfun() — with the graded rating scale model. It seems the scores are available for the GPCM and other models, but not the GRSM. I found some of the code that handles this but it's not clear why the scores aren't available for this model. Is there a way to obtain them?

**Comment by philchalmers** [comment]
Not all of the supported IRT model in mirt have been optimized with C++ code, which is why the `estfun()` doesn't support everything. It's possible to update `estfun()` to include R-based implementations of the require computations though (which would be slower, but more general and should be able to support custom item definitions). I'll consider adding this to the TODO list.
