### ISSUE TITLE
[BUG] Missing b-parameters are not shown at their right place

### ISSUE THREAD

**Issue by KGroskurth** [philchalmers/mirt#259]
Hi Phil, This might not be a bug, but we found it a bit unintuitive, so we thought it might be better to report it!

Actual state: We have seven answer options; thus, parameters b1 to b6 are estimated. Our data is sparse; just one person selected option 1 (from 1 to 7), so b1 cannot be estimated. However, in the output, we get values for b1 to b5, b6 is NA. This might be misread as b6 cannot be estimated, whereas, in fact, b1 cannot be estimated.

Desired state: It might be more intuitive to report NA for the specific b parameter that cannot be estimated (e.g., b1 in our example) than for b6 (in general).

Thank you (also for your fantastic package)!
Katharina

**Comment by philchalmers** [comment]
> Actual state: We have seven answer options; thus, parameters b1 to b6 are estimated. Our data is sparse; just one person selected option 1 (from 1 to 7), so b1 cannot be estimated. However, in the output, we get values for b1 to b5, b6 is NA. This might be misread as b6 cannot be estimated, whereas, in fact, b1 cannot be estimated.

I don't think that's true as parameters estimates borrow strength from their adjacent categories, though having only 1 response for the category will certainly inflate the sampling error. For example:

```r
library(mirt)
Science[Science[,1] == 1, 1] <- 2
Science[1,1] <- 1
apply(Science, 2, table)

mod <- mirt(Science, SE=TRUE)
coef(mod)
coef(mod, simplify=TRUE, IRTpars=TRUE)
````

Regarding your second point, if you remove a category from the data matrix then, regardless of the category, mirt doesn't really know which one was removed as the value of the observation is generally irrelevant (the distance between categories could go from 0 to 1 or 0 to 5, and mirt would just think of this as an ordinal step in either case).  This is admittedly a little jarring at first, but you should have seen a warning message that mirt remaps observations so that they all have the same integer pattern.

**Comment by KGroskurth** [comment]
Thank you for your quick reply! (And sorry for the confusion - I completely agree that parameters should not estimated if only very few respondents select a particular category.)
