### ISSUE TITLE
NA returned for response pattern with data

### ISSUE THREAD

**Issue by e-bartsch** [philchalmers/mirt#98]
Hey Phil,

I'm running into a problem with the `fscores` function. I'm getting an NA response and the following error message for a student who has answered 1308 out of 1404 questions in the model. 
```
Warning message:
NAs returned for response patterns with no data. Consider removing
```

This is how I'm calling the function: `fscores(mod_no_g, method='EAP', response.pattern=refresh_mirt_data[9323, ])`. The model is unidimensional. I'm happy to share the model and data with you if that's required.

Thank you!

**Comment by philchalmers** [comment]
Please do send along the data and model. If it's too sensitive to post publicly here then an email will do fine.

**Comment by philchalmers** [comment]
The problem here is rather technical, but the issue comes down to numerical stability required to compute the normalisation constant of the EAP estimates. Basically, the all log-likelihood values given the integration range are so small, that when they are exponentiation with `exp(LL)` they all will equal zero. Unfortunately, the exponentiation must occur, and basically a divide-by-zero issue comes up (there are other integration tricks going on behind the scenes, but that's the gist of it). I throw a warning message now when this occurs instead of just giving this weird behaviour. 

To avoid this, choose a method which does not require a normalisation constant, such as MAP, or ML. Basically any iterative scheme should work actually, because they are performed on a log-scale where things are numerically more stable.

**Comment by philchalmers** [comment]
Note that you'll still need to install the latest dev version, because I originally used EAP estimates as the starting values for the iterative methods (which clearly are problematic). This has been patched though to avoid this particular problem.

**Comment by e-bartsch** [comment]
Just installed the latest dev version and things are working now. Thanks for the quick help, Phil!
